/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLivestockRouteImport } from './routes/_app.livestock'
import { Route as AppFarmRouteImport } from './routes/_app.farm'
import { Route as AppAgentRouteImport } from './routes/_app.agent'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppLivestockMortalityRouteImport } from './routes/_app.livestock.mortality'
import { Route as AppLivestockMedicalRouteImport } from './routes/_app.livestock.medical'
import { Route as AppLivestockDashboardRouteImport } from './routes/_app.livestock.dashboard'
import { Route as AppLivestockBreedingRouteImport } from './routes/_app.livestock.breeding'
import { Route as AppLivestockAnimalsRouteImport } from './routes/_app.livestock.animals'
import { Route as AppFieldsIdRouteImport } from './routes/_app.fields.$id'
import { Route as AppAgentFieldsRouteImport } from './routes/_app.agent.fields'
import { Route as AppAgentDashboardRouteImport } from './routes/_app.agent.dashboard'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminFieldsRouteImport } from './routes/_app.admin.fields'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin.dashboard'
import { Route as AppLivestockAnimalsRegisterRouteImport } from './routes/_app.livestock.animals.register'
import { Route as AppLivestockAnimalsIdRouteImport } from './routes/_app.livestock.animals.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLivestockRoute = AppLivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmRoute = AppFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppLivestockMortalityRoute = AppLivestockMortalityRouteImport.update({
  id: '/mortality',
  path: '/mortality',
  getParentRoute: () => AppLivestockRoute,
} as any)
const AppLivestockMedicalRoute = AppLivestockMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AppLivestockRoute,
} as any)
const AppLivestockDashboardRoute = AppLivestockDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppLivestockRoute,
} as any)
const AppLivestockBreedingRoute = AppLivestockBreedingRouteImport.update({
  id: '/breeding',
  path: '/breeding',
  getParentRoute: () => AppLivestockRoute,
} as any)
const AppLivestockAnimalsRoute = AppLivestockAnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => AppLivestockRoute,
} as any)
const AppFieldsIdRoute = AppFieldsIdRouteImport.update({
  id: '/fields/$id',
  path: '/fields/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentFieldsRoute = AppAgentFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppAgentRoute,
} as any)
const AppAgentDashboardRoute = AppAgentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAgentRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFieldsRoute = AppAdminFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppLivestockAnimalsRegisterRoute =
  AppLivestockAnimalsRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AppLivestockAnimalsRoute,
  } as any)
const AppLivestockAnimalsIdRoute = AppLivestockAnimalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLivestockAnimalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agent': typeof AppAgentRouteWithChildren
  '/farm': typeof AppFarmRoute
  '/livestock': typeof AppLivestockRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/fields': typeof AppAdminFieldsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/agent/dashboard': typeof AppAgentDashboardRoute
  '/agent/fields': typeof AppAgentFieldsRoute
  '/fields/$id': typeof AppFieldsIdRoute
  '/livestock/animals': typeof AppLivestockAnimalsRouteWithChildren
  '/livestock/breeding': typeof AppLivestockBreedingRoute
  '/livestock/dashboard': typeof AppLivestockDashboardRoute
  '/livestock/medical': typeof AppLivestockMedicalRoute
  '/livestock/mortality': typeof AppLivestockMortalityRoute
  '/livestock/animals/$id': typeof AppLivestockAnimalsIdRoute
  '/livestock/animals/register': typeof AppLivestockAnimalsRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agent': typeof AppAgentRouteWithChildren
  '/farm': typeof AppFarmRoute
  '/livestock': typeof AppLivestockRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/fields': typeof AppAdminFieldsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/agent/dashboard': typeof AppAgentDashboardRoute
  '/agent/fields': typeof AppAgentFieldsRoute
  '/fields/$id': typeof AppFieldsIdRoute
  '/livestock/animals': typeof AppLivestockAnimalsRouteWithChildren
  '/livestock/breeding': typeof AppLivestockBreedingRoute
  '/livestock/dashboard': typeof AppLivestockDashboardRoute
  '/livestock/medical': typeof AppLivestockMedicalRoute
  '/livestock/mortality': typeof AppLivestockMortalityRoute
  '/livestock/animals/$id': typeof AppLivestockAnimalsIdRoute
  '/livestock/animals/register': typeof AppLivestockAnimalsRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/agent': typeof AppAgentRouteWithChildren
  '/_app/farm': typeof AppFarmRoute
  '/_app/livestock': typeof AppLivestockRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/fields': typeof AppAdminFieldsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/agent/dashboard': typeof AppAgentDashboardRoute
  '/_app/agent/fields': typeof AppAgentFieldsRoute
  '/_app/fields/$id': typeof AppFieldsIdRoute
  '/_app/livestock/animals': typeof AppLivestockAnimalsRouteWithChildren
  '/_app/livestock/breeding': typeof AppLivestockBreedingRoute
  '/_app/livestock/dashboard': typeof AppLivestockDashboardRoute
  '/_app/livestock/medical': typeof AppLivestockMedicalRoute
  '/_app/livestock/mortality': typeof AppLivestockMortalityRoute
  '/_app/livestock/animals/$id': typeof AppLivestockAnimalsIdRoute
  '/_app/livestock/animals/register': typeof AppLivestockAnimalsRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agent'
    | '/farm'
    | '/livestock'
    | '/notifications'
    | '/profile'
    | '/auth/complete-profile'
    | '/admin/dashboard'
    | '/admin/fields'
    | '/admin/users'
    | '/agent/dashboard'
    | '/agent/fields'
    | '/fields/$id'
    | '/livestock/animals'
    | '/livestock/breeding'
    | '/livestock/dashboard'
    | '/livestock/medical'
    | '/livestock/mortality'
    | '/livestock/animals/$id'
    | '/livestock/animals/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agent'
    | '/farm'
    | '/livestock'
    | '/notifications'
    | '/profile'
    | '/auth/complete-profile'
    | '/admin/dashboard'
    | '/admin/fields'
    | '/admin/users'
    | '/agent/dashboard'
    | '/agent/fields'
    | '/fields/$id'
    | '/livestock/animals'
    | '/livestock/breeding'
    | '/livestock/dashboard'
    | '/livestock/medical'
    | '/livestock/mortality'
    | '/livestock/animals/$id'
    | '/livestock/animals/register'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/_app/admin'
    | '/_app/agent'
    | '/_app/farm'
    | '/_app/livestock'
    | '/_app/notifications'
    | '/_app/profile'
    | '/auth/complete-profile'
    | '/_app/admin/dashboard'
    | '/_app/admin/fields'
    | '/_app/admin/users'
    | '/_app/agent/dashboard'
    | '/_app/agent/fields'
    | '/_app/fields/$id'
    | '/_app/livestock/animals'
    | '/_app/livestock/breeding'
    | '/_app/livestock/dashboard'
    | '/_app/livestock/medical'
    | '/_app/livestock/mortality'
    | '/_app/livestock/animals/$id'
    | '/_app/livestock/animals/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/livestock': {
      id: '/_app/livestock'
      path: '/livestock'
      fullPath: '/livestock'
      preLoaderRoute: typeof AppLivestockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farm': {
      id: '/_app/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof AppFarmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/livestock/mortality': {
      id: '/_app/livestock/mortality'
      path: '/mortality'
      fullPath: '/livestock/mortality'
      preLoaderRoute: typeof AppLivestockMortalityRouteImport
      parentRoute: typeof AppLivestockRoute
    }
    '/_app/livestock/medical': {
      id: '/_app/livestock/medical'
      path: '/medical'
      fullPath: '/livestock/medical'
      preLoaderRoute: typeof AppLivestockMedicalRouteImport
      parentRoute: typeof AppLivestockRoute
    }
    '/_app/livestock/dashboard': {
      id: '/_app/livestock/dashboard'
      path: '/dashboard'
      fullPath: '/livestock/dashboard'
      preLoaderRoute: typeof AppLivestockDashboardRouteImport
      parentRoute: typeof AppLivestockRoute
    }
    '/_app/livestock/breeding': {
      id: '/_app/livestock/breeding'
      path: '/breeding'
      fullPath: '/livestock/breeding'
      preLoaderRoute: typeof AppLivestockBreedingRouteImport
      parentRoute: typeof AppLivestockRoute
    }
    '/_app/livestock/animals': {
      id: '/_app/livestock/animals'
      path: '/animals'
      fullPath: '/livestock/animals'
      preLoaderRoute: typeof AppLivestockAnimalsRouteImport
      parentRoute: typeof AppLivestockRoute
    }
    '/_app/fields/$id': {
      id: '/_app/fields/$id'
      path: '/fields/$id'
      fullPath: '/fields/$id'
      preLoaderRoute: typeof AppFieldsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/fields': {
      id: '/_app/agent/fields'
      path: '/fields'
      fullPath: '/agent/fields'
      preLoaderRoute: typeof AppAgentFieldsRouteImport
      parentRoute: typeof AppAgentRoute
    }
    '/_app/agent/dashboard': {
      id: '/_app/agent/dashboard'
      path: '/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AppAgentDashboardRouteImport
      parentRoute: typeof AppAgentRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/fields': {
      id: '/_app/admin/fields'
      path: '/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AppAdminFieldsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/livestock/animals/register': {
      id: '/_app/livestock/animals/register'
      path: '/register'
      fullPath: '/livestock/animals/register'
      preLoaderRoute: typeof AppLivestockAnimalsRegisterRouteImport
      parentRoute: typeof AppLivestockAnimalsRoute
    }
    '/_app/livestock/animals/$id': {
      id: '/_app/livestock/animals/$id'
      path: '/$id'
      fullPath: '/livestock/animals/$id'
      preLoaderRoute: typeof AppLivestockAnimalsIdRouteImport
      parentRoute: typeof AppLivestockAnimalsRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminFieldsRoute: typeof AppAdminFieldsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminFieldsRoute: AppAdminFieldsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAgentRouteChildren {
  AppAgentDashboardRoute: typeof AppAgentDashboardRoute
  AppAgentFieldsRoute: typeof AppAgentFieldsRoute
}

const AppAgentRouteChildren: AppAgentRouteChildren = {
  AppAgentDashboardRoute: AppAgentDashboardRoute,
  AppAgentFieldsRoute: AppAgentFieldsRoute,
}

const AppAgentRouteWithChildren = AppAgentRoute._addFileChildren(
  AppAgentRouteChildren,
)

interface AppLivestockAnimalsRouteChildren {
  AppLivestockAnimalsIdRoute: typeof AppLivestockAnimalsIdRoute
  AppLivestockAnimalsRegisterRoute: typeof AppLivestockAnimalsRegisterRoute
}

const AppLivestockAnimalsRouteChildren: AppLivestockAnimalsRouteChildren = {
  AppLivestockAnimalsIdRoute: AppLivestockAnimalsIdRoute,
  AppLivestockAnimalsRegisterRoute: AppLivestockAnimalsRegisterRoute,
}

const AppLivestockAnimalsRouteWithChildren =
  AppLivestockAnimalsRoute._addFileChildren(AppLivestockAnimalsRouteChildren)

interface AppLivestockRouteChildren {
  AppLivestockAnimalsRoute: typeof AppLivestockAnimalsRouteWithChildren
  AppLivestockBreedingRoute: typeof AppLivestockBreedingRoute
  AppLivestockDashboardRoute: typeof AppLivestockDashboardRoute
  AppLivestockMedicalRoute: typeof AppLivestockMedicalRoute
  AppLivestockMortalityRoute: typeof AppLivestockMortalityRoute
}

const AppLivestockRouteChildren: AppLivestockRouteChildren = {
  AppLivestockAnimalsRoute: AppLivestockAnimalsRouteWithChildren,
  AppLivestockBreedingRoute: AppLivestockBreedingRoute,
  AppLivestockDashboardRoute: AppLivestockDashboardRoute,
  AppLivestockMedicalRoute: AppLivestockMedicalRoute,
  AppLivestockMortalityRoute: AppLivestockMortalityRoute,
}

const AppLivestockRouteWithChildren = AppLivestockRoute._addFileChildren(
  AppLivestockRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAgentRoute: typeof AppAgentRouteWithChildren
  AppFarmRoute: typeof AppFarmRoute
  AppLivestockRoute: typeof AppLivestockRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppFieldsIdRoute: typeof AppFieldsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAgentRoute: AppAgentRouteWithChildren,
  AppFarmRoute: AppFarmRoute,
  AppLivestockRoute: AppLivestockRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppFieldsIdRoute: AppFieldsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
